### ISSUE TITLE
Crashing on search

### ISSUE THREAD

**Issue by hongkongkiwi** [bashvtini/audiobookbay#1]
Whenever I try to do a search it crashes:
```
TypeError: Cannot read property 'replace' of undefined
    at Node.<anonymous> (/docker/audiobookbay/audiobookbay/controller/searchAudiobook.js:32:19)
    at initialize.exports.each (/docker/audiobookbay/audiobookbay/node_modules/cheerio/lib/api/traversing.js:300:24)
    at Request._callback (/docker/audiobookbay/audiobookbay/controller/searchAudiobook.js:21:38)
    at Request.self.callback (/docker/audiobookbay/audiobookbay/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/docker/audiobookbay/audiobookbay/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/docker/audiobookbay/audiobookbay/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
root@helios:/docker/audiobookbay/audiobookbay#
root@helios:/docker/audiobookbay/audiobookbay#
root@helios:/docker/audiobookbay/audiobookbay# node app.js
/docker/audiobookbay/audiobookbay/controller/searchAudiobook.js:32
                  .replace("/audio-books/", "/audiobook/");
                  ^
```

**Comment by bashvtini** [comment]
Hello hongkongkiwi!
I have refactored the code, hope i have fixed the issue.
